cantons:
    VS:
        - Brig-Glis
        - Eggerberg
        - Naters
        - Ried-Brig
        - Simplon
        - Termen
        - Zwischbergen
        - Ardon
        - Chamoson
        - Conthey
        - Nendaz
        - Vétroz
        - Bagnes
        - Bourg-Saint-Pierre
        - Liddes
        - Orsières
        - Sembrancher
        - Vollèges
        - Bellwald
        - Binn
        - Blitzingen
        - Ernen
        - Fiesch
        - Fieschertal
        - Lax
        - Niederwald
        - Grafschaft
        - Münster-Geschinen
        - Reckingen-Gluringen
        - Obergoms
        - Les Agettes
        - Ayent
        - Evolène
        - Hérémence
        - Saint-Martin (VS)
        - Vex
        - Mont-Noble
        - Agarn
        - Albinen
        - Ergisch
        - Inden
        - Leuk
        - Leukerbad
        - Oberems
        - Salgesch
        - Varen
        - Guttet-Feschel
        - Gampel-Bratsch
        - Turtmann-Unterems
        - Bovernier
        - Charrat
        - Fully
        - Isérables
        - Leytron
        - Martigny
        - Martigny-Combe
        - Riddes
        - Saillon
        - Saxon
        - Trient
        - Champéry
        - Collombey-Muraz
        - Monthey
        - Port-Valais
        - Saint-Gingolph
        - Troistorrents
        - Val-d'Illiez
        - Vionnaz
        - Vouvry
        - Bister
        - Bitsch
        - Grengiols
        - Riederalp
        - Ausserberg
        - Blatten
        - Bürchen
        - Eischoll
        - Ferden
        - Kippel
        - Niedergesteln
        - Raron
        - Unterbäch
        - Wiler (Lötschen)
        - Mörel-Filet
        - Steg-Hohtenn
        - Bettmeralp
        - Collonges
        - Dorénaz
        - Evionnaz
        - Finhaut
        - Massongex
        - Saint-Maurice
        - Salvan
        - Vernayaz
        - Vérossaz
        - Chalais
        - Chermignon
        - Chippis
        - Grône
        - Icogne
        - Lens
        - Miège
        - Mollens (VS)
        - Montana
        - Randogne
        - Saint-Léonard
        - Sierre
        - Venthône
        - Veyras
        - Anniviers
        - Arbaz
        - Grimisuat
        - Savièse
        - Sion
        - Veysonnaz
        - Baltschieder
        - Eisten
        - Embd
        - Grächen
        - Lalden
        - Randa
        - Saas-Almagell
        - Saas-Balen
        - Saas-Fee
        - Saas-Grund
        - St. Niklaus
        - Stalden (VS)
        - Staldenried
        - Täsch
        - Törbel
        - Visp
        - Visperterminen
        - Zeneggen
        - Zermatt
    VD:
        - Aigle
        - Bex
        - Chessel
        - Corbeyrier
        - Gryon
        - Lavey-Morcles
        - Leysin
        - Noville
        - Ollon
        - Ormont-Dessous
        - Ormont-Dessus
        - Rennaz
        - Roche (VD)
        - Villeneuve (VD)
        - Yvorne
        - Apples
        - Aubonne
        - Ballens
        - Berolle
        - Bière
        - Bougy-Villars
        - Féchy
        - Gimel
        - Longirod
        - Marchissy
        - Mollens (VD)
        - Montherod
        - Saint-George
        - Saint-Livres
        - Saint-Oyens
        - Saubraz
        - Avenches
        - Cudrefin
        - Faoug
        - Vully-les-Lacs
        - Bettens
        - Bournens
        - Boussens
        - La Chaux (Cossonay)
        - Chavannes-le-Veyron
        - Chevilly
        - Cossonay
        - Cottens (VD)
        - Cuarnens
        - Daillens
        - Dizy
        - Eclépens
        - Ferreyres
        - Gollion
        - Grancy
        - L'Isle
        - Lussery-Villars
        - Mauraz
        - Mex (VD)
        - Moiry
        - Mont-la-Ville
        - Montricher
        - Orny
        - Pampigny
        - Penthalaz
        - Penthaz
        - Pompaples
        - La Sarraz
        - Senarclens
        - Sévery
        - Sullens
        - Vufflens-la-Ville
        - Assens
        - Bercher
        - Bioley-Orjulaz
        - Bottens
        - Bretigny-sur-Morrens
        - Cugy (VD)
        - Echallens
        - Essertines-sur-Yverdon
        - Etagnières
        - Fey
        - Froideville
        - Morrens (VD)
        - Oulens-sous-Echallens
        - Pailly
        - Penthéréaz
        - Poliez-Pittet
        - Rueyres
        - Saint-Barthélemy (VD)
        - Villars-le-Terroir
        - Vuarrens
        - Montilliez
        - Goumoëns
        - Bonvillars
        - Bullet
        - Champagne
        - Concise
        - Corcelles-près-Concise
        - Fiez
        - Fontaines-sur-Grandson
        - Giez
        - Grandevent
        - Grandson
        - Mauborget
        - Mutrux
        - Novalles
        - Onnens (VD)
        - Provence
        - Sainte-Croix
        - Tévenon
        - Belmont-sur-Lausanne
        - Cheseaux-sur-Lausanne
        - Crissier
        - Epalinges
        - Jouxtens-Mézery
        - Lausanne
        - Le Mont-sur-Lausanne
        - Paudex
        - Prilly
        - Pully
        - Renens (VD)
        - Romanel-sur-Lausanne
        - Chexbres
        - Forel (Lavaux)
        - Lutry
        - Puidoux
        - Rivaz
        - Saint-Saphorin (Lavaux)
        - Savigny
        - Bourg-en-Lavaux
        - Aclens
        - Bremblens
        - Buchillon
        - Bussigny
        - Bussy-Chardonney
        - Chavannes-près-Renens
        - Chigny
        - Clarmont
        - Denens
        - Denges
        - Echandens
        - Echichens
        - Ecublens (VD)
        - Etoy
        - Lavigny
        - Lonay
        - Lully (VD)
        - Lussy-sur-Morges
        - Morges
        - Préverenges
        - Reverolle
        - Romanel-sur-Morges
        - Saint-Prex
        - Saint-Sulpice (VD)
        - Tolochenaz
        - Vaux-sur-Morges
        - Villars-Sainte-Croix
        - Villars-sous-Yens
        - Vufflens-le-Château
        - Vullierens
        - Yens
        - Boulens
        - Brenles
        - Bussy-sur-Moudon
        - Chavannes-sur-Moudon
        - Chesalles-sur-Moudon
        - Cremin
        - Curtilles
        - Dompierre (VD)
        - Forel-sur-Lucens
        - Hermenches
        - Lovatens
        - Lucens
        - Moudon
        - Ogens
        - Prévonloup
        - Rossenges
        - Sarzens
        - Syens
        - Villars-le-Comte
        - Vucherens
        - Montanaire
        - Arnex-sur-Nyon
        - Arzier-Le Muids
        - Bassins
        - Begnins
        - Bogis-Bossey
        - Borex
        - Chavannes-de-Bogis
        - Chavannes-des-Bois
        - Chéserex
        - Coinsins
        - Commugny
        - Coppet
        - Crans-près-Céligny
        - Crassier
        - Duillier
        - Eysins
        - Founex
        - Genolier
        - Gingins
        - Givrins
        - Gland
        - Grens
        - Mies
        - Nyon
        - Prangins
        - La Rippe
        - Saint-Cergue
        - Signy-Avenex
        - Tannay
        - Trélex
        - Le Vaud
        - Vich
        - L'Abergement
        - Agiez
        - Arnex-sur-Orbe
        - Ballaigues
        - Baulmes
        - Bavois
        - Bofflens
        - Bretonnières
        - Chavornay
        - Les Clées
        - Corcelles-sur-Chavornay
        - Croy
        - Juriens
        - Lignerolle
        - Montcherand
        - Orbe
        - La Praz
        - Premier
        - Rances
        - Romainmôtier-Envy
        - Sergey
        - Valeyres-sous-Rances
        - Vallorbe
        - Vaulion
        - Vuiteboeuf
        - Carrouge (VD)
        - Corcelles-le-Jorat
        - Essertes
        - Ferlens (VD)
        - Maracon
        - Mézières (VD)
        - Montpreveyres
        - Ropraz
        - Servion
        - Vulliens
        - Jorat-Menthue
        - Oron
        - Champtauroz
        - Chevroux
        - Corcelles-près-Payerne
        - Grandcour
        - Henniez
        - Missy
        - Payerne
        - Trey
        - Treytorrens (Payerne)
        - Villarzel
        - Valbroye
        - Château-d'Oex
        - Rossinière
        - Rougemont
        - Allaman
        - Bursinel
        - Bursins
        - Burtigny
        - Dully
        - Essertines-sur-Rolle
        - Gilly
        - Luins
        - Mont-sur-Rolle
        - Perroy
        - Rolle
        - Tartegnin
        - Vinzel
        - L'Abbaye
        - Le Chenit
        - Le Lieu
        - Blonay
        - Chardonne
        - Corseaux
        - Corsier-sur-Vevey
        - Jongny
        - Montreux
        - Saint-Légier-La Chiésaz
        - La Tour-de-Peilz
        - Vevey
        - Veytaux
        - Belmont-sur-Yverdon
        - Bioley-Magnoux
        - Chamblon
        - Champvent
        - Chavannes-le-Chêne
        - Chêne-Pâquier
        - Cheseaux-Noréaz
        - Cronay
        - Cuarny
        - Démoret
        - Donneloye
        - Ependes (VD)
        - Essert-Pittet
        - Mathod
        - Molondin
        - Montagny-près-Yverdon
        - Oppens
        - Orges
        - Orzens
        - Pomy
        - Rovray
        - Suchy
        - Suscévaz
        - Treycovagnes
        - Ursins
        - Valeyres-sous-Montagny
        - Valeyres-sous-Ursins
        - Villars-Epeney
        - Vugelles-La Mothe
        - Yverdon-les-Bains
        - Yvonand
    GE:
        - Aire-la-Ville
        - Anières
        - Avully
        - Avusy
        - Bardonnex
        - Bellevue
        - Bernex
        - Carouge (GE)
        - Cartigny
        - Céligny
        - Chancy
        - Chêne-Bougeries
        - Chêne-Bourg
        - Choulex
        - Collex-Bossy
        - Collonge-Bellerive
        - Cologny
        - Confignon
        - Corsier (GE)
        - Dardagny
        - Genève
        - Genthod
        - Le Grand-Saconnex
        - Gy
        - Hermance
        - Jussy
        - Laconnex
        - Lancy
        - Meinier
        - Meyrin
        - Onex
        - Perly-Certoux
        - Plan-les-Ouates
        - Pregny-Chambésy
        - Presinge
        - Puplinge
        - Russin
        - Satigny
        - Soral
        - Thônex
        - Troinex
        - Vandoeuvres
        - Vernier
        - Versoix
        - Veyrier
    FR:
        - Bussy (FR)
        - Châbles
        - Châtillon (FR)
        - Cheiry
        - Cheyres
        - Cugy (FR)
        - Domdidier
        - Dompierre (FR)
        - Estavayer-le-Lac
        - Fétigny
        - Gletterens
        - Léchelles
        - Lully (FR)
        - Ménières
        - Montagny (FR)
        - Morens (FR)
        - Murist
        - Nuvilly
        - Prévondavaux
        - Rueyres-les-Prés
        - Russy
        - Saint-Aubin (FR)
        - Sévaz
        - Surpierre
        - Vallon
        - Villeneuve (FR)
        - Vuissens
        - Les Montets
        - Delley-Portalban
        - Vernay
        - Auboranges
        - Billens-Hennens
        - Chapelle (Glâne)
        - Le Châtelard
        - Châtonnaye
        - Ecublens (FR)
        - Grangettes
        - Massonnens
        - Mézières (FR)
        - Montet (Glâne)
        - Romont (FR)
        - Rue
        - Siviriez
        - Ursy
        - Villaz-Saint-Pierre
        - Vuisternens-devant-Romont
        - Villorsonnens
        - Torny
        - La Folliaz
        - Haut-Intyamon
        - Pont-en-Ogoz
        - Botterens
        - Broc
        - Bulle
        - Châtel-sur-Montsalvens
        - Corbières
        - Crésuz
        - Echarlens
        - Grandvillard
        - Gruyères
        - Hauteville
        - Jaun
        - Marsens
        - Morlon
        - Le Pâquier (FR)
        - Pont-la-Ville
        - Riaz
        - La Roche
        - Sâles
        - Sorens
        - Vaulruz
        - Vuadens
        - Bas-Intyamon
        - Val-de-Charmey
        - Arconciel
        - Autafond
        - Autigny
        - Avry
        - Belfaux
        - Chénens
        - Chésopelloz
        - Corminboeuf
        - Corpataux-Magnedens
        - Corserey
        - Cottens (FR)
        - Ependes (FR)
        - Farvagny
        - Ferpicloz
        - Fribourg
        - Givisiez
        - Granges-Paccot
        - Grolley
        - Marly
        - Matran
        - Neyruz (FR)
        - Noréaz
        - Pierrafortscha
        - Ponthaux
        - Le Mouret
        - Prez-vers-Noréaz
        - Rossens (FR)
        - Le Glèbe
        - Senèdes
        - Treyvaux
        - Villars-sur-Glâne
        - Villarsel-sur-Marly
        - Vuisternens-en-Ogoz
        - Hauterive (FR)
        - La Brillaz
        - La Sonnaz
        - Barberêche
        - Courgevaux
        - Courlevon
        - Courtepin
        - Cressier (FR)
        - Fräschels
        - Galmiz
        - Gempenach
        - Greng
        - Gurmels
        - Jeuss
        - Kerzers
        - Kleinbösingen
        - Lurtigen
        - Meyriez
        - Misery-Courtion
        - Muntelier
        - Murten
        - Ried bei Kerzers
        - Salvenach
        - Ulmiz
        - Villarepos
        - Bas-Vully
        - Haut-Vully
        - Wallenried
        - Alterswil
        - Brünisried
        - Düdingen
        - Giffers
        - Bösingen
        - Heitenried
        - Oberschrot
        - Plaffeien
        - Plasselb
        - Rechthalten
        - St. Antoni
        - St. Silvester
        - St. Ursen
        - Schmitten (FR)
        - Tafers
        - Tentlingen
        - Ueberstorf
        - Wünnewil-Flamatt
        - Zumholz
        - Attalens
        - Bossonnens
        - Châtel-Saint-Denis
        - Granges (Veveyse)
        - Remaufens
        - Saint-Martin (FR)
        - Semsales
        - Le Flon
        - La Verrerie
    NE:
        - Bevaix
        - Boudry
        - Brot-Dessous
        - Corcelles-Cormondrèche
        - Cortaillod
        - Fresens
        - Gorgier
        - Montalchez
        - Peseux
        - Rochefort
        - Saint-Aubin-Sauges
        - Vaumarcus
        - Milvignes
        - La Chaux-de-Fonds
        - Les Planchettes
        - La Sagne
        - Les Brenets
        - La Brévine
        - Brot-Plamboz
        - Le Cerneux-Péquignot
        - La Chaux-du-Milieu
        - Le Locle
        - Les Ponts-de-Martel
        - Cornaux
        - Cressier (NE)
        - Enges
        - Hauterive (NE)
        - Le Landeron
        - Lignières
        - Neuchâtel
        - Saint-Blaise
        - La Tène
        - Valangin
        - Val-de-Ruz
        - La Côte-aux-Fées
        - Les Verrières
        - Val-de-Travers
    JU:
        - Boécourt
        - Bourrignon
        - Châtillon (JU)
        - Corban
        - Courchapoix
        - Courrendlin
        - Courroux
        - Courtételle
        - Delémont
        - Develier
        - Ederswiler
        - Mervelier
        - Mettembert
        - Movelier
        - Pleigne
        - Rebeuvelier
        - Rossemaison
        - Saulcy
        - Soyhières
        - Vellerat
        - Haute-Sorne
        - Val Terbi
        - Le Bémont (JU)
        - Les Bois
        - Les Breuleux
        - La Chaux-des-Breuleux
        - Les Enfers
        - Les Genevez (JU)
        - Lajoux (JU)
        - Montfaucon
        - Muriaux
        - Le Noirmont
        - Saignelégier
        - Saint-Brais
        - Soubey
        - Alle
        - Beurnevésin
        - Boncourt
        - Bonfol
        - Bure
        - Coeuve
        - Cornol
        - Courchavon
        - Courgenay
        - Courtedoux
        - Damphreux
        - Fahy
        - Fontenais
        - Grandfontaine
        - Lugnez
        - Porrentruy
        - Rocourt
        - Vendlincourt
        - Basse-Allaine
        - Clos du Doubs
        - Haute-Ajoie
        - La Baroche