<?php

namespace Maidmaid\WebotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NumberplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberplateRepository extends EntityRepository
{
}
